title: damagethundercat.github.io
description: 워크숍 공동 블로그
url: "https://damagethundercat.github.io"
baseurl: ""
timezone: Asia/Seoul

permalink: /:year/:title.html
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CONTRIBUTING.md
  - vendor
